apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-test
  description: A python app, based on the Streamlit web framework
  tags:
    - python
    - streamlit
  links:
    - url: https://python-test.tap-gitops.tanzu.dk
      title: App Url
      icon: dashboard
    - url: https://docs.streamlit.io
      title: Streamlit Documentation
      icon: dashboard
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=python-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: denmark-team
  system: demo
  dependsOn:
    - resource:default/fastapi-test
