apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-test
  links:
    - url: http://python-test.default.tap.tanzu.dk
      title: Demo App
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-accelerator
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/TanzuDK/python-test.git
      ref:
        branch: main
